server:
  port: 8083 #服务端口

#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  #MAPPER中简化包名
  typeAliasesPackage: com/hua
  mapperLocations: classpath*:mapper/*.xml
  #开启驼峰转换
  configuration:
    mapUnderscoreToCamelCase: true

---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.105:3306/videoplateform?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:oracle:thin:@21.8.129.135:1521:nctest
    #username: dev_autoins
    #password: abc
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 20
    # 配置获取连接等待超时的时间，配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    #max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validationQuery: SELECT 1 FROM DUAL
    # 空闲时检测连接是否有效
    test-while-idle: true
    # 申请连接时检测连接是否有效，会降低性能
    test-on-borrow: false
    # 归还连接时检测连接是否有效，会降低性能
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    spring.datasource.connectionProperties=druid.stat.mergeSql: true;druid.stat.slowSqlMillis=5000

  freemarker:
    #req访问request
    request-context-attribute: req
    #后缀名
    suffix: .ftl
    content-type: text/html
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:/templates/
    #编码格式
    charset: UTF-8
    settings:
    #数字格式化，无小数点
      number_format: '0.##'

cms:
  dbname: hua
  dbtype: mysql

